#!/bin/bash

# Create build directory if it doesn't exist
mkdir -p build

# Run LaTeX to generate the .aux file and other resources
lualatex -output-directory=build main.tex
# Run Biber to process the bibliography
biber build/main
# Run LaTeX again to resolve references
lualatex -output-directory=build main.tex
# Generate the index
mendex build/main
# Final LaTeX pass to finalize the document
lualatex -output-directory=build main.tex
# Remove auxiliary files generated by LaTeX
rm -f build/main.aux build/main.bbl build/main.bcf build/main.blg build/main.idx build/main.ilg build/main.ind build/main.lof build/main.log build/main.lot build/main.out build/main.run.xml build/main.toc
