lualatex main.tex   # Run LaTeX to generate the .aux file and other resources
biber main          # Run Biber to process the bibliography
lualatex main.tex   # Run LaTeX again to resolve references
mendex main         # Generate the index
lualatex main.tex   # Final LaTeX pass to finalize the document
# Remove auxiliary files generated by LaTeX
rm -f main.aux main.bbl main.bcf main.blg main.idx main.ilg main.ind main.lof main.log main.lot main.out main.run.xml main.toc