name: Build LaTeX Document

on:
  push:  # 全てのブランチで実行
  pull_request:  # プルリクエスト時にも実行

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 22.04 LTS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install required LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-luatex latexmk texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-xetex

    - name: Build LaTeX document with lualatex
      run: |
        ./build.sh # ビルドスクリプトの実行
      env:
        HOME: /github/home  # ホームディレクトリエラーを防ぐための設定

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: build/main.pdf  # ビルドされたPDFの場所
