name: Build LaTeX Document and Upload to Google Drive

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install required LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-luatex biber texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-xetex texlive-lang-cjk mendexk \
          fonts-noto-cjk  # Noto Sans CJK JP フォントのインストール

    - name: Make build script executable
      run: chmod +x build.sh

    - name: Build LaTeX document
      run: ./build.sh

    - name: Debug build folder
      run: ls -al build

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Google Drive API library
      run: pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

    - name: Upload to Google Drive
      env:
        GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}"
      run: |
        python <<EOF
        import os
        import json
        from google.oauth2 import service_account
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload

        # シークレットから認証情報をJSON形式で取得
        credentials_info = json.loads(os.environ['GOOGLE_APPLICATION_CREDENTIALS'])

        # Google Drive API認証
        creds = service_account.Credentials.from_service_account_info(
            credentials_info,
            scopes=['https://www.googleapis.com/auth/drive.file']
        )

        drive_service = build('drive', 'v3', credentials=creds)

        # アップロードするGoogle DriveのフォルダID
        folder_id = "1sze5HxFJMdntN8H9GUrdXhiQbhFeUA22"

        # PDFファイルのメタデータ設定
        file_metadata = {
            'name': 'main.pdf',  # Google Drive上でのファイル名
            'parents': [folder_id]  # 指定したフォルダにアップロード
        }

        # PDFファイルのアップロード
        media = MediaFileUpload('build/main.pdf', mimetype='application/pdf')
        file = drive_service.files().create(body=file_metadata, media_body=media, fields='id').execute()

        print(f"Uploaded file with ID: {file.get('id')}")
        EOF
