name: Build LaTeX Document

on:
  push:  # 全てのブランチで実行
  pull_request:  # プルリクエスト時にも実行

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 22.04 LTS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install required LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-luatex biber texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-xetex texlive-lang-cjk mendexk

    - name: Make build script executable
      run: chmod +x build.sh

    - name: Build LaTeX document
      run: ./build.sh

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf  # Artifacts名
        path: build/*.pdf  # PDFファイルを指定
